Filter out symlinks in _get_file_matching()
Due to the rootfs changes, kernel/initrd are shipped with unversioned symlinks now.
The number of files is now 2 at minimum (symlink and real file).

Fix the following error:
ValueError: Too many files matching '/tmp/tmpq2xWZQ/rootfs/binary/boot/Image*' found.

Regression introduced in:
https://git.linaro.org/ci/ubuntu-build-service.git/commitdiff/9d07c7b60f18c207b9b446e1f3bb2eedf8ad4876

Change-Id: I0235dcd1e0faa9c6159345b1f35987f7fa8fe4fb
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
Reported-by: Mathieu Poirier <mathieu.poirier@linaro.org>